name: kyc
description: "Customer identity verification project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  go_router: ^16.2.1
  flutter_bloc: ^9.1.1
  bloc: ^9.0.0
  get_it: ^8.2.0
  dio: ^5.9.0
  freezed: ^3.2.3
  freezed_annotation: ^3.1.0
  flutter_secure_storage: ^9.2.4
  connectivity_plus: ^7.0.0
  image_picker: ^1.2.0
  google_mlkit_text_recognition: ^0.15.0
  uuid: ^4.5.1
  encrypt: ^5.0.3
  hive_flutter: ^1.1.0
  http: ^1.5.0
  path_provider: ^2.1.5
  meta: ^1.16.0
  http_certificate_pinning: ^3.0.1
  crypto: ^3.0.6
  pointycastle: ^3.9.1
  asn1lib: ^1.6.5
  http_parser: ^4.1.2
  mime: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.8.0

flutter:
  uses-material-design: true
  assets:
     - assets/config/config.json